export enum TransactionType {
  ACH_INCOMING = "ACH_INCOMING",
  ACH_OUTGOING = "ACH_OUTGOING",
  POS = "POS",
  P2P_SEND = "P2P_SEND",
  P2P_RECEIVE = "P2P_RECEIVE",
  WIRE_OUTGOING = "WIRE_OUTGOING",
  WIRE_INCOMING = "WIRE_INCOMING",
  FEE = "FEE",
}

export enum TransactionStatus {
  PROCESSING = "PROCESSING",
  PENDING = "PENDING",
  SETTLED = "SETTLED",
  RETURNED = "RETURNED",
  FAILED = "FAILED",
}